export const documentWorkflow = {
  DRAFT: ['SUBMITTED'],
  SUBMITTED: ['UNDER_REVIEW'],
  UNDER_REVIEW: ['REVIEWED', 'REJECTED'],
  REVIEWED: ['PENDING_APPROVAL'],
  PENDING_APPROVAL: ['APPROVED', 'REJECTED'],
  APPROVED: ['EFFECTIVE'],
  EFFECTIVE: ['OBSOLETE'],
  REJECTED: ['DRAFT'],
  OBSOLETE: []
};
